before_install: gem install bundler
before_script:
  - "bundle exec rake test_app"
script: "DISPLAY=:99.0 bundle exec rspec spec"
branches:
  only:
    - master
notifications:
  email:
    - jdyer@spreecommerce.com
    - brian@spreecommerce.com
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
